---
# tasks file for ansible-role-docker-container-registry

- name: docker_container - {{ docker_container_registry_volume_dir }}/auth
  ansible.builtin.file:
    path: "{{ docker_container_registry_volume_dir }}/auth"
    state: directory
  when: 
   - docker_container_registry_basic_auth_enable is defined
   - docker_container_registry_basic_auth_enable

- name: docker_container {{ docker_image_registry_name }} htpasswd 
  community.general.htpasswd:
    crypt_scheme: bcrypt
    name: "{{ docker_container_registry_basic_auth_username }}"
    path: "{{ docker_container_registry_volume_dir }}/auth/htpasswd"
    password: "{{ docker_container_registry_basic_auth_password }}"
    state: present
  when: 
    - docker_container_registry_basic_auth_enable is defined
    - docker_container_registry_basic_auth_enable

- name: docker_image pull {{ docker_image_registry_name }}
  community.docker.docker_image:
    name: '{{ docker_image_registry_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_registry_pull

- name: docker_network {{ docker_container_registry_name }}
  community.docker.docker_network:
    name: "{{ docker_network_registry_name }}"
    driver: "{{ docker_network_registry_driver | default('bridge') }}"
    attachable: "{{ docker_network_registry_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_registry_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_registry_internal | default(false) }}"
    state: present


- name: docker_container {{ docker_container_registry_name }}
  community.docker.docker_container:
    name: "{{ docker_container_registry_name }}"
    comparisons: "{{ docker_container_registry_comparisons }}"
    image: "{{ docker_container_registry_image }}"
    state: "{{ docker_container_registry_state | default('started') }}"
    recreate: "{{ docker_container_registry_recreate | default(false) }}"
    restart: "{{ docker_container_registry_restart | default(false) }}"
    restart_policy: "{{ docker_container_registry_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_registry_auto_remove | default(false) }}"
    detach: "{{ docker_container_registry_detach | default(true) }}"
    init: "{{ docker_container_registry_init | default(false) }}"
    interactive: "{{ docker_container_registry_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_registry_keep_volumes | default(true) }}"
    memory: "{{ docker_container_registry_memory | default('0') }}"
    paused: "{{ docker_container_registry_paused | default(false) }}"
    privileged: "{{ docker_container_registry_privileged | default(false) }}"
    read_only: "{{ docker_container_registry_read_only | default(false) }}"
    tty: "{{ docker_container_registry_tty | default(false) }}"
    env_file: "{{ docker_container_registry_env_file | default(omit) }}"
    env: "{{ docker_container_registry_env | default(omit) }}"
    volumes: "{{ docker_container_registry_volumes | default(omit) }}"
    labels: "{{ docker_container_registry_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_registry_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_registry_name }}"
    pull: "{{ docker_container_registry_pull | default(false) }}"
    networks: "{{ docker_container_registry_networks }}"
    published_ports: "{{ docker_container_registry_ports | default(omit) }}"
